(()=>{
  const D=window.IA_GUIDE_DATA;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const order=['biplane','airship','cargo_airship','bamboo_hopper','gyrodyne','quadrocopter','warship'];
  const roleMeta={inventory:['Storage',''],boiler:['Fuel / boiler','B'],booster:['Booster','+'],weapon:['Weapon','W'],upgrade:['Upgrade','U'],banner:['Banner','F'],dye:['Dye','D']};
  const item=id=>D.items[id]||{id,name:id.split(':').pop().replaceAll('_',' '),category:'vanilla',tooltip:[],icon:null};
  const icon=id=>{const m=item(id),d=document.createElement('span');d.className='item-icon';const t=document.createElement('span');t.className='item-fallback';t.textContent=m.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();d.append(t);if(m.icon){const im=new Image();im.alt='';im.onload=()=>t.remove();im.onerror=()=>im.remove();im.src=m.icon;d.prepend(im)}return d};
  const progress=$('#progress'), header=$('#header');
  const onScroll=()=>{const h=document.documentElement;progress.style.transform=`scaleX(${h.scrollTop/Math.max(1,h.scrollHeight-h.clientHeight)})`;header.classList.toggle('is-scrolled',scrollY>24)};addEventListener('scroll',onScroll,{passive:true});onScroll();
  const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));
  const viewer=new IAAircraftViewer($('#viewerStage')); let current='biplane'; let auto=true;
  function selectAircraft(name){current=name;const a=D.aircraft[name],idx=order.indexOf(name);$('#aircraftIndex').textContent=`${String(idx+1).padStart(2,'0')} / 07`;$('#aircraftName').textContent=a.name;$('#aircraftDescription').textContent=a.description;const counts={};a.slots.forEach(s=>counts[s.type]=(counts[s.type]||0)+1);$('#aircraftFacts').innerHTML=`<div><span>Seats</span><strong>${Object.keys(a.seatLocators||{}).length}</strong></div><div><span>Slots</span><strong>${a.slots.length}</strong></div><div><span>Mass</span><strong>${a.stats.mass}</strong></div><div><span>Fuel factor</span><strong>${a.stats.fuel}</strong></div>`;const has=!!window.IA_MODEL_DATA?.[name];$('#modelNote').textContent=has?'3D preview uses the converted Bedrock geometry from the alpha asset baseline.':'This aircraft is documented here; its cloth-heavy browser model is intentionally not loaded on this guide page.';$('#viewerStage').classList.toggle('viewer-unavailable',!has);if(has){viewer.load(name);viewer.setAutorotate(auto);viewer.setVar('engine_power',.8);viewer.setVar('cloth_motion',.65)}$$('.aircraft-tab').forEach(b=>b.classList.toggle('active',b.dataset.aircraft===name))}
  order.forEach(name=>{const a=D.aircraft[name],b=document.createElement('button');b.className='aircraft-tab';b.dataset.aircraft=name;b.innerHTML=`<b>${a.name}</b><span>${a.model3d?'3D preview':'Guide data'}</span>`;b.onclick=()=>selectAircraft(name);$('#aircraftTabs').append(b)});$('#autoOrbit').onclick=e=>{auto=!auto;viewer.setAutorotate(auto);e.currentTarget.textContent=`Auto orbit: ${auto?'on':'off'}`};setTimeout(()=>selectAircraft('biplane'),80);
  const byResult=new Map(D.recipes.map(r=>[r.result.item,r]));let filter='all',selected;
  const filters=['all','aircraft','component','upgrade','weapon'];filters.forEach(f=>{const b=document.createElement('button');b.className='recipe-filter'+(f==='all'?' active':'');b.textContent=f;b.onclick=()=>{filter=f;$$('.recipe-filter').forEach(x=>x.classList.toggle('active',x===b));renderRecipeList()};$('#recipeFilters').append(b)});
  const ing=(r,ch)=>{const x=r.key[ch];return x?.item||x?.tag||null};
  function renderRecipeList(){const q=$('#recipeSearch').value.toLowerCase().trim(),box=$('#recipeList');box.innerHTML='';D.recipes.filter(r=>{const m=item(r.result.item);return(filter==='all'||m.category===filter)&&(!q||m.name.toLowerCase().includes(q)||r.slug.includes(q))}).forEach(r=>{const m=item(r.result.item),b=document.createElement('button');b.className='recipe-entry'+(selected===r?' active':'');b.append(icon(r.result.item));const s=document.createElement('span');s.innerHTML=`<b>${m.name}</b><small>${m.category} · shaped</small>`;b.append(s);b.onclick=()=>selectRecipe(r);box.append(b)})}
  function expand(id,q=1,out={},stack=new Set()){const r=byResult.get(id);if(!r||stack.has(id)){out[id]=(out[id]||0)+q;return out}const next=new Set(stack);next.add(id);const c={};r.pattern.join('').split('').filter(x=>x!==' ').forEach(ch=>{const k=ing(r,ch);if(k)c[k]=(c[k]||0)+1});for(const [k,n] of Object.entries(c)){if(byResult.has(k))expand(k,q*n,out,next);else out[k]=(out[k]||0)+q*n}return out}
  function craftSlot(id){const d=document.createElement('div');d.className='craft-slot';if(id)d.append(icon(id));return d}
  function selectRecipe(r){selected=r;const m=item(r.result.item);$('#recipeCategory').textContent=m.category;$('#recipeTitle').textContent=m.name;const g=$('#craftGrid');g.innerHTML='';for(const row of r.pattern)for(const ch of row)g.append(craftSlot(ch===' '?null:ing(r,ch)));const res=$('#craftResult');res.innerHTML='';const rs=document.createElement('div');rs.className='result-slot';rs.append(icon(r.result.item));res.append(rs);$('#recipeNote').textContent=(m.tooltip||[]).join(' ')||'Current alpha shaped recipe.';const totals=expand(r.result.item);const tb=$('#recipeTotals');tb.innerHTML='';Object.entries(totals).sort((a,b)=>item(a[0]).name.localeCompare(item(b[0]).name)).forEach(([id,n])=>{const c=document.createElement('div');c.className='ingredient-chip';c.append(icon(id));const t=document.createElement('span');t.textContent=`${n}× ${item(id).name}`;c.append(t);tb.append(c)});renderRecipeList()}
  $('#recipeSearch').oninput=renderRecipeList;renderRecipeList();selectRecipe(D.recipes.find(r=>r.slug==='biplane'));
  order.forEach(name=>{const o=document.createElement('option');o.value=name;o.textContent=D.aircraft[name].name;$('#inventoryAircraft').append(o)});
  function renderInventory(name){const a=D.aircraft[name],ui=$('#inventoryUI');$('#inventoryTitle').textContent=`${a.name} inventory`;ui.innerHTML='';let xs=a.slots.map(s=>s.x),ys=a.slots.map(s=>s.y);let minX=Math.min(...xs)-10,maxX=Math.max(...xs)+30,minY=Math.min(...ys)-10,maxY=Math.max(...ys)+30;const W=maxX-minX,H=maxY-minY;for(const s of a.slots){const d=document.createElement('div'),meta=roleMeta[s.type]||[s.type,''];d.className=`slot ${s.type}`;d.dataset.short=meta[1];d.title=`Slot ${s.index}: ${meta[0]}`;d.style.left=`${((s.x-minX)/W)*88+6}%`;d.style.top=`${((s.y-minY)/H)*78+14}%`;ui.append(d)}const counts={};a.slots.forEach(s=>counts[s.type]=(counts[s.type]||0)+1);$('#slotLegend').innerHTML='';for(const [type,n] of Object.entries(counts)){const m=roleMeta[type]||[type,''];const r=document.createElement('div');r.className='legend-row';r.innerHTML=`<i class="legend-dot slot ${type}"></i><b>${m[0]}</b><span>${n} slot${n===1?'':'s'}</span>`;$('#slotLegend').append(r)}$('#inventorySummary').textContent=`${a.slots.length} logical slots · ${Object.keys(a.seatLocators||{}).length} seat locator${Object.keys(a.seatLocators||{}).length===1?'':'s'} · source layout preserved in the port data.`}
  $('#inventoryAircraft').onchange=e=>renderInventory(e.target.value);renderInventory('biplane');
  function gyro(){const speed=+$('#gyroSpeed').value,alt=+$('#gyroAlt').value,hdg=+$('#gyroHeading').value,pitch=+$('#gyroPitch').value,roll=+$('#gyroRoll').value;$('#outSpeed').textContent=speed.toFixed(1);$('#outAlt').textContent=Math.round(alt);$('#outHeading').textContent=String(Math.round(hdg)).padStart(3,'0')+'°';$('#gyroHorizon').style.transform=`translateY(${pitch*1.4}px) rotate(${-roll}deg)`}['gyroSpeed','gyroAlt','gyroHeading','gyroPitch','gyroRoll'].forEach(id=>$('#'+id).oninput=gyro);gyro();
})();