(()=>{
  const DEG=Math.PI/180;
  const MATH={sin:x=>Math.sin(x*DEG),cos:x=>Math.cos(x*DEG),sqrt:Math.sqrt,random:(a=0,b=1)=>a+(b-a)*.5};
  const I=()=>new Float32Array([1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1]);
  function mul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let v=0;for(let k=0;k<4;k++)v+=a[k*4+r]*b[c*4+k];o[c*4+r]=v}return o}
  function T(x,y,z){const m=I();m[12]=x;m[13]=y;m[14]=z;return m}
  function S(x,y,z){const m=I();m[0]=x;m[5]=y;m[10]=z;return m}
  function RX(a){const m=I(),c=Math.cos(a),s=Math.sin(a);m[5]=c;m[6]=s;m[9]=-s;m[10]=c;return m}
  function RY(a){const m=I(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[2]=-s;m[8]=s;m[10]=c;return m}
  function RZ(a){const m=I(),c=Math.cos(a),s=Math.sin(a);m[0]=c;m[1]=s;m[4]=-s;m[5]=c;return m}
  function Rxyz(r){return mul(mul(RZ((r?.[2]||0)*DEG),RY((r?.[1]||0)*DEG)),RX((r?.[0]||0)*DEG))}
  function transform(m,x,y,z){return [m[0]*x+m[4]*y+m[8]*z+m[12],m[1]*x+m[5]*y+m[9]*z+m[13],m[2]*x+m[6]*y+m[10]*z+m[14]]}
  function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far),o=new Float32Array(16);o[0]=f/aspect;o[5]=f;o[10]=(far+near)*nf;o[11]=-1;o[14]=2*far*near*nf;return o}
  function norm(v){const l=Math.hypot(...v)||1;return v.map(x=>x/l)}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function dot(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]}
  function lookAt(eye,target=[0,0,0],up=[0,1,0]){const z=norm([eye[0]-target[0],eye[1]-target[1],eye[2]-target[2]]),x=norm(cross(up,z)),y=cross(z,x),o=I();o[0]=x[0];o[1]=y[0];o[2]=z[0];o[4]=x[1];o[5]=y[1];o[6]=z[1];o[8]=x[2];o[9]=y[2];o[10]=z[2];o[12]=-dot(x,eye);o[13]=-dot(y,eye);o[14]=-dot(z,eye);return o}
  function compileValue(value){if(typeof value==='number')return()=>value;if(typeof value!=='string')return()=>0;let e=value.replace(/q\.property\('ia_assets:([^']+)'\)/g,(_,k)=>`(P[${JSON.stringify(k)}]??0)`).replace(/\bv\.([A-Za-z_]\w*)/g,(_,k)=>`(V[${JSON.stringify(k)}]??0)`).replace(/math\.sin/g,'M.sin').replace(/math\.cos/g,'M.cos').replace(/math\.sqrt/g,'M.sqrt').replace(/math\.random/g,'M.random');try{const fn=new Function('V','P','M',`"use strict";return (${e});`);return(V,P)=>{try{const v=+fn(V,P,MATH);return Number.isFinite(v)?v:0}catch{return 0}}}catch{return()=>0}}
  function compileVec(a,def=[0,0,0]){a=Array.isArray(a)?a:def;return[0,1,2].map(i=>compileValue(a[i]??def[i]))}
  function faceVerts(cube,face){const o=cube.origin||[0,0,0],s=cube.size||[0,0,0],f=cube.inflate||0,x0=o[0]-f,y0=o[1]-f,z0=o[2]-f,x1=o[0]+s[0]+f,y1=o[1]+s[1]+f,z1=o[2]+s[2]+f;return({north:[[x1,y0,z0],[x0,y0,z0],[x0,y1,z0],[x1,y1,z0]],south:[[x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1]],west:[[x0,y0,z0],[x0,y0,z1],[x0,y1,z1],[x0,y1,z0]],east:[[x1,y0,z1],[x1,y0,z0],[x1,y1,z0],[x1,y1,z1]],up:[[x0,y1,z1],[x1,y1,z1],[x1,y1,z0],[x0,y1,z0]],down:[[x0,y0,z0],[x1,y0,z0],[x1,y0,z1],[x0,y0,z1]]})[face]||[]}
  function faceUV(fd,tw,th){const uv=fd?.uv||[0,0],sz=fd?.uv_size||[1,1],u0=uv[0]/tw,u1=(uv[0]+sz[0])/tw,v0=1-uv[1]/th,v1=1-(uv[1]+sz[1])/th;return[[u0,v1],[u1,v1],[u1,v0],[u0,v0]]}
  function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
  function program(gl,vs,fs){const p=gl.createProgram();gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vs));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p}
  class IAAircraftViewer{
    constructor(el){this.el=el;this.canvas=document.createElement('canvas');this.canvas.setAttribute('aria-label','3D aircraft model');this.gl=this.canvas.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:false});if(!this.gl){el.innerHTML='<div class="viewer-loading">WebGL is unavailable. Recipes, inventory and instruments still work.</div>';return}el.appendChild(this.canvas);this.layers={};this.current=null;this.showSeats=false;this.playing=true;this.autorotate=true;this.orbit={yaw:.55,pitch:.32,dist:7};this.drag=null;this.vars={engine_rotation:0,pressing_interpolated_x:0,pressing_interpolated_y:0,pressing_interpolated_z:0,time:0,velocity_x:.18,velocity_y:.03,velocity_z:.22,turret_cooldown:0,chest:0,turret_pitch:0,turret_yaw:0,balloon_pitch:0,balloon_roll:0};this.props={visual_pitch:0,visual_roll:0,engine_power:.72,cloth_motion:.75,airborne:1};this.last=performance.now();this.center=[0,0,0];this.setupGL();this.bind();this.resize();window.addEventListener('resize',()=>this.resize());requestAnimationFrame(t=>this.loop(t))}
    setupGL(){const gl=this.gl;this.prog=program(gl,'attribute vec3 a;attribute vec2 u;uniform mat4 m;varying vec2 v;void main(){v=u;gl_Position=m*vec4(a,1.0);}','precision mediump float;uniform sampler2D t;varying vec2 v;void main(){vec4 c=texture2D(t,v);if(c.a<0.04)discard;gl_FragColor=c;}');this.posLoc=gl.getAttribLocation(this.prog,'a');this.uvLoc=gl.getAttribLocation(this.prog,'u');this.mvpLoc=gl.getUniformLocation(this.prog,'m');this.texLoc=gl.getUniformLocation(this.prog,'t');this.pointProg=program(gl,'attribute vec3 a;uniform mat4 m;void main(){gl_Position=m*vec4(a,1.0);gl_PointSize=11.0;}','precision mediump float;void main(){vec2 p=gl_PointCoord-vec2(.5);if(dot(p,p)>.25)discard;gl_FragColor=vec4(1.0,.78,.28,1.0);}');this.pointPosLoc=gl.getAttribLocation(this.pointProg,'a');this.pointMvpLoc=gl.getUniformLocation(this.pointProg,'m');gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);this.white=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.white);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([210,190,150,255]))}
    bind(){const c=this.canvas;c.addEventListener('pointerdown',e=>{this.drag={x:e.clientX,y:e.clientY,yaw:this.orbit.yaw,pitch:this.orbit.pitch};c.setPointerCapture?.(e.pointerId)});c.addEventListener('pointermove',e=>{if(!this.drag)return;this.orbit.yaw=this.drag.yaw-(e.clientX-this.drag.x)*.007;this.orbit.pitch=Math.max(-1.2,Math.min(1.2,this.drag.pitch-(e.clientY-this.drag.y)*.006));this.autorotate=false});c.addEventListener('pointerup',()=>this.drag=null);c.addEventListener('pointercancel',()=>this.drag=null);c.addEventListener('wheel',e=>{e.preventDefault();this.orbit.dist=Math.max(.8,Math.min(50,this.orbit.dist*Math.exp(e.deltaY*.001)))},{passive:false})}
    resize(){if(!this.gl)return;const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(this.el.clientWidth*d)),h=Math.max(1,Math.floor(this.el.clientHeight*d));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}this.gl.viewport(0,0,w,h)}
    makeTexture(url){const gl=this.gl,t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([205,186,151,255]));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);if(url){const im=new Image();im.onload=()=>{gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,im);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST_MIPMAP_NEAREST)};im.crossOrigin='anonymous';im.src=url}return t}
    compileAnimation(anims){const first=Object.values(anims||{})[0];this.anim={};if(!first)return;for(const [n,r] of Object.entries(first.bones||{})){this.anim[n]={};if(r.rotation)this.anim[n].rot=compileVec(r.rotation);if(r.position)this.anim[n].pos=compileVec(r.position);if(r.scale)this.anim[n].scale=compileVec(r.scale,[1,1,1])}}
    buildLayer(layer,g){const gl=this.gl,bones=g.bones||[],byName=Object.fromEntries(bones.map(b=>[b.name,b])),boneNames=bones.map(b=>b.name),boneIndex=Object.fromEntries(boneNames.map((n,i)=>[n,i])),chunks=[];const tw=g.description?.texture_width||64,th=g.description?.texture_height||64;for(const b of bones){const bp=b.pivot||[0,0,0],bi=boneIndex[b.name];for(const c of b.cubes||[]){const cp=c.pivot||bp,cubeM=mul(T((cp[0]-bp[0])/16,(cp[1]-bp[1])/16,(cp[2]-bp[2])/16),Rxyz(c.rotation||[0,0,0]));for(const [fname,fd] of Object.entries(c.uv||{})){const vv=faceVerts(c,fname),uv=faceUV(fd,tw,th);if(vv.length!==4)continue;const ord=[0,1,2,0,2,3];for(const j of ord){const p=[(vv[j][0]-cp[0])/16,(vv[j][1]-cp[1])/16,(vv[j][2]-cp[2])/16],q=transform(cubeM,...p);chunks.push({p:q,uv:uv[j],bi})}}}}
      const local=new Float32Array(chunks.length*3),uvs=new Float32Array(chunks.length*2),bis=new Uint16Array(chunks.length);chunks.forEach((v,i)=>{local.set(v.p,i*3);uvs.set(v.uv,i*2);bis[i]=v.bi});const positions=new Float32Array(local.length);const posBuf=gl.createBuffer(),uvBuf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,uvBuf);gl.bufferData(gl.ARRAY_BUFFER,uvs,gl.STATIC_DRAW);gl.bindBuffer(gl.ARRAY_BUFFER,posBuf);gl.bufferData(gl.ARRAY_BUFFER,positions,gl.DYNAMIC_DRAW);
      return{alias:layer.alias,visible:layer.defaultVisible!==false,texture:this.makeTexture(layer.texture),g,byName,boneNames,boneIndex,local,uvs,bis,positions,posBuf,uvBuf,world:new Array(bones.length)}}
    boneMatrices(L){const done={};const calc=n=>{const i=L.boneIndex[n];if(done[n])return L.world[i];const b=L.byName[n],pp=b.parent?(L.byName[b.parent]?.pivot||[0,0,0]):[0,0,0],bp=b.pivot||[0,0,0],a=this.anim[n]||{},avPos=a.pos?a.pos.map(f=>f(this.vars,this.props)): [0,0,0],avRot=a.rot?a.rot.map(f=>f(this.vars,this.props)): [0,0,0],avSc=a.scale?a.scale.map(f=>f(this.vars,this.props)): [1,1,1],base=b.rotation||[0,0,0];let local=mul(T((bp[0]-pp[0]+avPos[0])/16,(bp[1]-pp[1]+avPos[1])/16,(bp[2]-pp[2]+avPos[2])/16),mul(Rxyz([base[0]+avRot[0],base[1]+avRot[1],base[2]+avRot[2]]),S(avSc[0],avSc[1],avSc[2])));L.world[i]=b.parent?mul(calc(b.parent),local):local;done[n]=true;return L.world[i]};L.boneNames.forEach(calc)}
    updatePositions(L){this.boneMatrices(L);const p=L.positions,l=L.local,b=L.bis,c=this.center;for(let i=0;i<b.length;i++){const q=transform(L.world[b[i]],l[i*3],l[i*3+1],l[i*3+2]);p[i*3]=q[0]-c[0];p[i*3+1]=q[1]-c[1];p[i*3+2]=q[2]-c[2]}const gl=this.gl;gl.bindBuffer(gl.ARRAY_BUFFER,L.posBuf);gl.bufferSubData(gl.ARRAY_BUFFER,0,p)}
    load(name){if(!this.gl)return;this.current=name;this.layers={};const b=window.IA_MODEL_DATA[name];this.compileAnimation(b.animations);for(const l of b.layers){const g=b.geometries[l.geometryId];if(g)this.layers[l.alias]=this.buildLayer(l,g)}this.center=[0,0,0];this.layersList=Object.values(this.layers);this.layersList.forEach(L=>this.updatePositions(L));let mn=[Infinity,Infinity,Infinity],mx=[-Infinity,-Infinity,-Infinity];for(const L of this.layersList.filter(x=>x.visible)){const p=L.positions;for(let i=0;i<p.length;i+=3){for(let k=0;k<3;k++){mn[k]=Math.min(mn[k],p[i+k]);mx[k]=Math.max(mx[k],p[i+k])}}}this.center=mn.map((v,i)=>(v+mx[i])/2);this.layersList.forEach(L=>this.updatePositions(L));const span=mx.map((v,i)=>v-mn[i]),r=Math.max(...span)*.55||3;this.orbit.dist=Math.max(3,r*2.15);this.orbit.yaw=.65;this.orbit.pitch=.28;const seats=window.IA_DATA.aircraft[name].seatLocators||{};this.seats=Object.values(seats).flatMap(v=>[v[0]-this.center[0],v[1]-this.center[1],v[2]-this.center[2]]);this.seatBuf=this.gl.createBuffer();this.gl.bindBuffer(this.gl.ARRAY_BUFFER,this.seatBuf);this.gl.bufferData(this.gl.ARRAY_BUFFER,new Float32Array(this.seats),this.gl.STATIC_DRAW);this.el.querySelector('.viewer-loading')?.remove()}
    setLayer(a,on){if(this.layers[a])this.layers[a].visible=!!on}setSeats(on){this.showSeats=!!on}setPlaying(on){this.playing=!!on}setAutorotate(on){this.autorotate=!!on}setVar(n,v){if(n in this.props)this.props[n]=+v;else this.vars[n]=+v}
    frameMVP(){const w=this.canvas.width,h=this.canvas.height,o=this.orbit,cp=Math.cos(o.pitch),sp=Math.sin(o.pitch),cy=Math.cos(o.yaw),sy=Math.sin(o.yaw),eye=[o.dist*sy*cp,o.dist*sp,o.dist*cy*cp],view=lookAt(eye),proj=perspective(36*DEG,w/Math.max(1,h),.01,500),model=RY(Math.PI);return mul(proj,mul(view,model))}
    render(){const gl=this.gl;if(!gl)return;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const mvp=this.frameMVP();gl.useProgram(this.prog);gl.uniformMatrix4fv(this.mvpLoc,false,mvp);gl.uniform1i(this.texLoc,0);for(const L of Object.values(this.layers)){if(!L.visible)continue;this.updatePositions(L);gl.bindBuffer(gl.ARRAY_BUFFER,L.posBuf);gl.enableVertexAttribArray(this.posLoc);gl.vertexAttribPointer(this.posLoc,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,L.uvBuf);gl.enableVertexAttribArray(this.uvLoc);gl.vertexAttribPointer(this.uvLoc,2,gl.FLOAT,false,0,0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,L.texture||this.white);gl.drawArrays(gl.TRIANGLES,0,L.bis.length)}if(this.showSeats&&this.seats?.length){gl.useProgram(this.pointProg);gl.uniformMatrix4fv(this.pointMvpLoc,false,mvp);gl.bindBuffer(gl.ARRAY_BUFFER,this.seatBuf);gl.enableVertexAttribArray(this.pointPosLoc);gl.vertexAttribPointer(this.pointPosLoc,3,gl.FLOAT,false,0,0);gl.drawArrays(gl.POINTS,0,this.seats.length/3)}}
    loop(t){if(!this.gl)return;const dt=Math.min(.05,(t-this.last)/1000||0);this.last=t;if(this.autorotate&&!this.drag)this.orbit.yaw+=dt*.12;if(this.playing){this.vars.time+=dt;this.vars.engine_rotation=(this.vars.engine_rotation+dt*3.6*(this.props.engine_power||0))%36}this.resize();this.render();requestAnimationFrame(x=>this.loop(x))}
  }
  window.IAAircraftViewer=IAAircraftViewer;
})();